name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.1

    - name: Terraform plan
      run: |
        if [[ $GITHUB_BASE_REF == *"develop"* ]]; then
          cd infra/dev
          echo "Using DEV environment"
          echo "Showing current directory" ### TODO:Borrar linea
          pwd ### TODO:Borrar linea
          # terraform init
          # terraform validate
          # terraform plan
        elif [[ $GITHUB_BASE_REF == *"main"* ]]; then
          cd infra/pro
          echo "Using PRO environment"
          # terraform init
          # terraform validate
          # terraform plan
        else
          echo "Unknown environment"
          exit 1
        fi

    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        approvers: JaimeVillarF
        secret: ${{ github.TOKEN }}

    - name: Terraform apply
      run: |
        if [[ $GITHUB_BASE_REF == *"develop"* ]]; then
          cd infra/dev
          echo "Deploying DEV environment"
          # terraform apply -auto-approve
        elif [[ $GITHUB_BASE_REF == *"main"* ]]; then
          cd infra/pro
          echo "Deploying PRO environment"
          # terraform apply -auto-approve
        else
          echo "Unknown environment"
          exit 1
        fi

    - name: Build and test Lambda
      run: |
        docker build -t lambda-image .
        docker run -t lambda-image