name: CICD Docker + TF

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker - Build and test Lambda
      run: |
        docker build -t lambda-image .
        docker run -t lambda-image

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.1

    - name: Terraform plan
      run: |
        if [[ $GITHUB_BASE_REF == *"develop"* ]]; then
          echo "Using DEV environment"
          cd infra/dev
          # terraform init
          # terraform validate
          # terraform plan
        elif [[ $GITHUB_BASE_REF == *"main"* ]]; then
          echo "Using PRO environment"
          cd infra/pro
          # terraform init
          # terraform validate
          # terraform plan
        else
          echo "Unknown environment"
          exit 1
        fi

  deploy:
    name: deploy
    runs-on: Ubuntu-latest
    needs: build
    environment:
      name: Deploy TF
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform apply
        run: |
          if [[ $GITHUB_BASE_REF == *"develop"* ]]; then
            echo "Deploying DEV environment"
            cd infra/dev
            # terraform apply -auto-approve
          elif [[ $GITHUB_BASE_REF == *"main"* ]]; then
            echo "Deploying PRO environment"
            cd infra/pro
            # terraform apply -auto-approve
          else
            echo "Unknown environment"
            exit 1
          fi